In [26]:
#MERGE DFs: WebScrapping - DataBase

import pandas as pd
import numpy as np
import re

#df_total, quitar filas de nulos

#Import df_web_scrapping, full

df_web_scrapping = pd.read_csv('/Users/MIGUEL/Desktop/CLAB1/Ironhack-Module-1-Project---Pipelines-/data/processed/df_web_scrapping.csv')
df_total = pd.read_csv('/Users/MIGUEL/Desktop/CLAB1/Ironhack-Module-1-Project---Pipelines-/data/processed/df_totalCLEAN.csv')


#Replacement of 'None' values by NaN in country column

df_total.country.replace('None', np.nan, regex=True, inplace=True)

#Drop Null values in df_total - column: country
df_total.country.isnull().sum()
df_no_null_values = df_total[df_total.age.isnull()]
df_no_null_values.shape

df_total.drop(df_total[df_total.country.isnull()].index, inplace = True)
df_total.shape

df_total.country.isnull().sum()

#Merge - df_total,no null values in country col with df_web_scrapping:

df_project2 = pd.merge(df_web_scrapping, df_total, on=['country', 'country'])

#Exportin to processed:

df_project2.to_csv('/Users/MIGUEL/Desktop/CLAB1/Ironhack-Module-1-Project---Pipelines-/data/processed/df_project2CLEAN.csv', index=False)
df_project2

,Rank,country,Population,% of World Population,Date,Source_x,age,gender,image,name,position,Source_y,worth BUSD,worthChange millions USD
0,1,China,"1,400,795,960",18.1%,8 Jan 2020,National population clock,55,Male,https://specials-images.forbesimg.com/imageser...,li shufu,92,Automotive ==> automobiles,15,0
1,1,China,"1,400,795,960",18.1%,8 Jan 2020,National population clock,48,None,https://specials-images.forbesimg.com/imageser...,lei jun,118,Technology ==> smartphones,12,0
2,1,China,"1,400,795,960",18.1%,8 Jan 2020,National population clock,48,Male,https://specials-images.forbesimg.com/imageser...,pan zhengmin,156,Technology ==> electronics,9,0
3,1,China,"1,400,795,960",18.1%,8 Jan 2020,National population clock,72,Male,https://specials-images.forbesimg.com/imageser...,zong qinghou,161,Food and Beverage ==> beverages,9,0
4,1,China,"1,400,795,960",18.1%,8 Jan 2020,National population clock,51,None,https://specials-images.forbesimg.com/imageser...,guo guangchang,187,Diversified ==> conglomerate,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646,136,Qatar,"2,747,282",0.0354%,30 Sep 2019,Monthly National estimate[128],58,None,https://specials-images.forbesimg.com/imageser...,hamad bin jassim bin jaber al thani,1867,Finance and Investments ==> investments,1,0
647,157,Cyprus,"875,900",0.0113%,31 Dec 2018,National annual estimate[148],51,None,https://specials-images.forbesimg.com/imageser...,stelios haji-ioannou,1506,Service ==> EasyJet,1,0
648,157,Cyprus,"875,900",0.0113%,31 Dec 2018,National annual estimate[148],47,Female,https://specials-images.forbesimg.com/imageser...,clelia haji-ioannou,1779,Service ==> EasyJet,1,0
649,157,Cyprus,"875,900",0.0113%,31 Dec 2018,National annual estimate[148],63,None,https://specials-images.forbesimg.com/imageser...,surendra hiranandani,1784,Real Estate ==> real estate,1,0
650,171,Iceland,"362,860",0.00468%,30 Sep 2019,National quarterly estimate[162],51,None,https://specials-images.forbesimg.com/imageser...,thor bjorgolfsson,1219,Diversified ==> investments,2,0